#!/usr/bin/env sh
# create a plaintext file

echo "some plaintext" > ptext

# generate random keys (of the same size: if they're too small, the XOR wraps
# around)

COUNT="$(wc -c ptext | cut -d ' ' -f 1)"

for I in 1 2 3 4
do
	dd bs=1 count="${COUNT}" if=/dev/urandom of="key${I}"
done

# generate a ciphertext

xor key* ptext > ctext

# regenerate the plaintext

xor key* ctext > ptext.recovered

# compare

diff ptext*

